lesson2 finished
redhemd/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-25 10:22 UTC by redhemd

2021-09-26 08:42 UTC, AlexPavlof commented
<img width="798" alt="image" src="https://user-images.githubusercontent.com/1210257/134800484-711b0d56-7cf7-4fa1-8517-b4bd0b954378.png">
У меня так это выглядит, проверь, пожалуйста

2021-09-26 08:53 UTC, AlexPavlof requested changes

2021-09-26 08:53 UTC, AlexPavlof commented on index.html
> +        <!-- <div id="app"></div>
Закомментированный код лучше не оставлять

2021-09-26 08:53 UTC, AlexPavlof commented on src/css/style.css
> +/* #app {
Мы называем это мёртвым кодом :)

2021-09-26 08:53 UTC, AlexPavlof commented on src/css/style.css
> +    width: 60%;
OK. Понятно, почему такой результат вышел на скриншоте.

Смотри. Стараться сделать идеальную вёрстку для абсолютно любого размера экрана — это задача из разряда невозможного. Для адаптивной вёрстки принято пользоваться брейкпоинтами через медиа-запросы. Так вёрстка будет вести себя намного более предсказуемо.

В макете указаны конкретные величины, предлагаю использовать их.

2021-09-26 09:34 UTC, redhemd commented on src/css/style.css
> +    width: 60%;
Добрый день,

Изначально я верстал на размер экрана 100% на локальном файле, затем когда я это запустил в нашем проекте, запустив через npm run dev, страница открылась на размере 75%, и верстка поехала как на вашем скрине выше :)
![01](https://user-images.githubusercontent.com/58127576/134801877-6df31ad7-70c1-4b2e-85e2-d94292390082.jpg)

Поэтому я все переделал, на размер 75% экрана монитора, потому что, когда вы откроете его на своем экране, и там тоже будет 75%. Вопрос: мне все-таки нужно будет переделать, и если да, то где в макете смотреть конкретные величины?

2021-09-27 06:20 UTC, AlexPavlof approved these changes

2021-09-27 07:45 UTC, redhemd commented on src/css/style.css
> +    width: 1440px;
Добрый день, я взял width: 1440px; из макета :) Какое значение можно взять чтобы было правильно?

2021-09-27 07:46 UTC, redhemd commented on src/css/style.css
> +    position: absolute;
Исправил :)

2021-09-27 07:50 UTC, redhemd commented on src/css/style.css
> +    background-color: rgba(0, 0, 0, 0.6);
Исправил

2021-09-27 07:51 UTC, redhemd commented on src/css/style.css
> +    left: 200px;
Исправил!

2021-09-27 07:53 UTC, redhemd commented on src/css/style.css
> +    margin: 16px 0;
Убрал

2021-09-27 07:53 UTC, redhemd commented on src/css/style.css
> +    background-color: lightblue;
Исправил

2021-09-27 07:53 UTC, redhemd commented on src/css/style.css
> +    right: 25px;
Все исправил

2021-09-27 07:54 UTC, merged