Rewrited all code according bem and scss
redhemd/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-06 10:40 UTC by redhemd

2021-10-07 10:02 UTC, AlexPavlof requested changes

2021-10-07 10:02 UTC, AlexPavlof commented on src/assets/kolesa-logo.svg
> +<svg version="1.2" baseProfile="tiny-ps" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 430 70" width="430" height="70">
Расскажи, как ты сохраняешь SVG?

2021-10-07 10:02 UTC, AlexPavlof commented on src/css/style.css
> +*,
Этот файл всё ещё нужен?

2021-10-07 10:02 UTC, AlexPavlof commented on src/scss/blocks/footer-blocks/footer-info.scss
> +    & .social-icons {
Это отдельный блок

2021-10-07 10:02 UTC, AlexPavlof commented on src/scss/style.scss
> +*,
Давай этот код из файла тоже вынесем в какой-нибудь `layout.scss`

2021-10-07 10:02 UTC, AlexPavlof commented on src/scss/vars.scss
> +$white: white;
`#fff`

2021-10-07 10:02 UTC, AlexPavlof commented on src/scss/vars.scss
> +$light-grey: rgb(196, 194, 194);
в HEX

2021-10-07 10:02 UTC, AlexPavlof commented on src/scss/vars.scss
> +$blue: #2a81dd;
Если называть цвета, как они названы в макете, в них проще будет ориентироваться

![image](https://user-images.githubusercontent.com/1210257/136338976-bff885a8-338e-418a-8b79-b0be18a8ccaa.png)

2021-10-07 10:02 UTC, AlexPavlof commented on src/scss/vars.scss
> +$border-color: #1c18191a;
Есть встроенный миксин: `transparentize($color, $amount);` (или fade-out)

```scss
background-color: transparentize(#1c1819, .3);
background-color: transparentize($black-primary, .3);
```

https://sass-lang.com/documentation/modules/color#transparentize

2021-10-07 12:46 UTC, redhemd commented on src/assets/kolesa-logo.svg
> +<svg version="1.2" baseProfile="tiny-ps" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 430 70" width="430" height="70">
1. выбираю в фигме элемент
2. выбираю copy as svg
![image](https://user-images.githubusercontent.com/58127576/136386581-e6efe900-ce99-438b-b9ae-f6cff615d3c9.png)
3. в фотошопе вставляю, и экспортирую как svg

2021-10-08 07:09 UTC, redhemd commented on src/css/style.css
> +*,
вроде без него все смещается

2021-10-08 07:13 UTC, redhemd commented on src/scss/blocks/footer-blocks/footer-info.scss
> +    & .social-icons {
+

2021-10-08 07:14 UTC, redhemd commented on src/scss/style.scss
> +*,
вынес

2021-10-08 07:15 UTC, redhemd commented on src/scss/vars.scss
> +$white: white;
исправил

2021-10-08 07:16 UTC, redhemd commented on src/scss/vars.scss
> +$light-grey: rgb(196, 194, 194);
исправил

2021-10-08 07:47 UTC, redhemd commented on src/scss/vars.scss
> +$border-color: #1c18191a;
исправил

2021-10-12 11:06 UTC, merged