rewrited all on vue
redhemd/Kolesa-Upgrade-FE-2021 pull request #7
Opened 2021-10-20 12:59 UTC by redhemd

Перенес весь код на вью, до дедлайна постараюсь все сделать на с директивами и компонентами.

2021-10-25 04:06 UTC, AlexPavlof requested changes

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +<div class="good-types body-main-block__good-types">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/1210257/138627134-cf8e832d-bead-4ded-8803-b0dc89a4191a.png">

Можно сделать по такому принципу:
```javascript
types: [
    {
        name: 'Все товары',
        value: 'all',
    },
    ...
],
```

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +<input type="radio" name="type" id="all-goods"  value="0" v-model="picked" checked>
Тут получится примерно так `:value="type.value"`

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +<input type="radio" name="type" id="clothes" value="1" v-model="picked">
`picked`, конечно, коротко, но не совсем понятно. Переменным лучше давать осмысленные названия, чтобы без знания всего кода было понятно, откуда в них значения. Если типы товаров названы `types`, то выбранный тип может быть `pickedType` или `selectedType`

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +<div class="card-products js__cards">
Зачем тебе понадобилось три одинаковых блока со всеми товарами и с каждой категорией можно понять. Но зачем понадобилось два блока со всеми товарами?

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +      selectedTab: 0,
Не нашёл, где используется

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +    clear() {
Зачем?

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
> +    closeModal() {
Не используется реактивность

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
>  <template>
OK. Давай по-быстрому пробежимся по основной логике и vue.

1. Исходные данные. В коде для работы и отображения ты используешь три отдельных массива. И кажется, что упростить это никак нельзя. Но представь ситуацию, если у тебя будет не три категории товаров, а десять. Придется десять раз повторять шаблон? Гораздо проще использовать один массив. Но тут возникает момент с фильтрацией, как отфильтровать нужные товары? Добавь к товарам ключ для категорий.

2. Реактивность. Vue — это не только логика в вёрстке. Vue — это и реактивность, которая у тебя не используется. Например, для отображения модалок ты используешь DOM, но можно завести свойство в `data`, например, `isShowModal`, и использовать его для отображения/скрытия модальных окон. В шаблоне к модалкам просто добавляешь `v-if="isShowModal"`. А в методах отображения/скрытия меняешь true-false.

3. Вычисляемые свойства. computed-свойства — мощная возможность в фреймворке, которую даже многие опытные разработчики избегают (ну, или не знают как использовать). Возможно, они кажутся сложными для понимания, но если их рассматривать как гетеры в объектах, то всё встанет на свои места. Если есть пробелы в этом места, посмотри в учебнике по JavaScript раздел про геттеры.

Давай вернёмся к исходным данным. Для работы тебе необходимы: массивы с товарами (с добавленными категориями в них), массив типов товаров, выбранный тип товара. Выбранный тип товара меняется при клике на фильтр, принимает значения `all`, `clothes`, `accessories`. Создай один массив с товарами и работай только с ним, забудь про три отдельных массива.

```javascript
computed: {
    allProducts() {
        return { ...this.clothes, ...this. accessories };
    },
},
```

Вычисляемые свойства удобно делать атомарными, то есть одно свойство — одна операция.
```javascript
computed: {
    filteredProducts() {
        if (this.selectedType === 'all') return this.allProducts;

        return this.allProducts.filter((product) => product.category === this.selectedType);
    },
    sortedProducts() {
        return this.filteredProducts.sort(<твой метод сортировки isNew>);
    },
},
```
В шаблоне ты будешь теперь работать только с `sortedProducts`. Тебе не придётся дублировать код в шаблоне. Значения автоматически будут вычисляться только на основе выбранного типа товара.

2021-10-25 04:06 UTC, AlexPavlof commented on vue-kolesa-upgrade/src/App.vue
>  </style>
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1210257/138632973-46d7db2d-30c6-4494-8879-c7d6615fd6f0.png">
Не могу закрыть окно

2021-10-26 05:03 UTC, AlexPavlof approved these changes

2021-10-26 09:43 UTC, merged

2021-10-26 10:18 UTC, redhemd commented on vue-kolesa-upgrade/src/App.vue
> +<input type="radio" name="type" id="all-goods"  value="0" v-model="picked" checked>
Первые два комментария не совсем понял, если я туда циклом vfor все данные задаю, у меня в консоли ошибок много, хотя код также продолжает работать

2021-10-26 10:18 UTC, redhemd commented on vue-kolesa-upgrade/src/App.vue
> +<input type="radio" name="type" id="clothes" value="1" v-model="picked">
исправил

2021-10-26 10:19 UTC, redhemd commented on vue-kolesa-upgrade/src/App.vue
> +<div class="card-products js__cards">
это исправил в новом комите

2021-10-26 10:19 UTC, redhemd commented on vue-kolesa-upgrade/src/App.vue
> +      selectedTab: 0,
исправил

2021-10-26 10:19 UTC, redhemd commented on vue-kolesa-upgrade/src/App.vue
> +    clear() {
исправил

2021-10-26 12:02 UTC, redhemd commented on vue-kolesa-upgrade/src/App.vue
>  </style>
у меня модалка не адаптивная, а fixed к центру экрана, хотел уточнить как это можно исправить, заново сверстать?